
import { JsonProperty, JsonClassType } from 'jackson-js';


export class AlphaSettingsResponse {

  @JsonProperty() @JsonClassType({type: () => [Number]})
    code: number;

  @JsonProperty() @JsonClassType({type: () => [Map]})
    data: Map<string, unknown>;
}

/**
export class AlphaData {

    @JsonProperty() @JsonClassType({type: () => [Number]})
      code: number;

    }

{
    "code": 200,
    "info": "Success",
    "data": {
        "sys_sn": "AE3100520050057",
        "ems_version": "V1.01.95D",
        "charge_workdays": "0000000",
        "grid_charge": 0,
        "time_chaf1a": "00:00",
        "time_chae1a": "00:00",
        "time_chaf2a": "00:00",
        "time_chae2a": "00:00",
        "bakbox_ver": "V2.49",
        "ctr_dis": 0,
        "time_disf1a": "00:00",
        "time_dise1a": "00:00",
        "time_disf2a": "00:00",
        "time_dise2a": "00:00",
        "bat_high_cap": 100.00,
        "bat_use_cap": 11.00,
        "charge_weekend": "0000000",
        "grid_Charge_we": 0,
        "time_cha_fwe1a": "00:00",
        "time_cha_ewe1a": "00:00",
        "time_cha_fwe2a": "00:00",
        "time_cha_ewe2a": "00:00",
        "bat_highcap_we": 0.00,
        "ctr_dis_we": 0,
        "time_dis_fwe1a": "00:00",
        "time_dis_ewe1a": "00:00",
        "time_dis_fwe2a": "00:00",
        "time_dis_ewe2a": "00:00",
        "bat_usecap_we": 0.00,
        "basic_mode_jp": 0,
        "peace_mode_jp": 0,
        "vpp_mode_jp": 0,
        "channel1": "0",
        "control_mode1": "",
        "start_time1a": "",
        "end_time1a": "",
        "start_time1b": "",
        "end_time1b": "",
        "date1": "0000000",
        "charge_soc1": "",
        "ups1": "0",
        "switch_on1": 0,
        "switch_off1": 0,
        "delay1": "0",
        "duration1": "0",
        "pause1": "0",
        "channel2": "0",
        "control_mode2": "",
        "start_time2a": "",
        "end_time2a": "",
        "start_time2b": "",
        "end_time2b": "",
        "date2": "0000000",
        "charge_soc2": "",
        "ups2": "0",
        "switch_on2": 0,
        "switch_off2": 0,
        "delay2": "0",
        "duration2": "0",
        "pause2": "0",
        "l1_priority": 1,
        "l2_priority": 2,
        "l3_priority": 3,
        "l1_soc_limit": 0.00,
        "l2_soc_limit": 0.00,
        "l3_soc_limit": 0.00,
        "charge_mode2": 1,
        "charge_mode1": 1,
        "backupbox": 0,
        "minv": "Storion-SMILE-T10",
        "mbat": "M4856-S",
        "generator": 0,
        "gc_output_mode": 0,
        "generator_mode": 0,
        "gc_soc_start": 10,
        "gc_soc_end": 10,
        "gc_time_start": 0,
        "gc_time_end": 0,
        "gc_charge_power": 1,
        "gc_rated_power": 0,
        "dg_cap": 0,
        "dg_frequency": 50,
        "gc_rate_percent": 80,
        "chargingpile": null,
        "currentsetting": 0.00,
        "chargingmode": 0,
        "charging_pile_list": null,
        "chargingpile_control_open": 1,
        "peak_fill_en": 0,
        "peakvalue": 20.0,
        "fillvalue": 0.0,
        "delta": 1.0,
        "peak_s1a": "00:00",
        "peak_e1a": "00:00",
        "peak_s2a": "00:00",
        "peak_e2a": "00:00",
        "fill_s1a": "00:00",
        "fill_e1a": "00:00",
        "fill_s2a": "00:00",
        "fill_e2a": "00:00",
        "pm_offset": 0.0,
        "pm_max": 0.0,
        "pm_offset_en": 0,
        "pm_offset_s1a": "00:00",
        "pm_offset_e1a": "00:00",
        "pm_offset_s2a": "00:00",
        "pm_offset_e2a": "00:00",
        "stoinv_type": 1,
        "loadcut_soc": 10,
        "loadtied_soc": 11,
        "ac_tied": 0,
        "soc_50_flag": 0,
        "auto_soccalib_en": 0,
        "three_unbalance_en": 0,
        "enable_current_set": null,
        "enable_obc_set": null,
        "ems_platform": "",
        "storage_breaker_specs": 32,
        "storageBreakerSpecsFlag": 0,
        "upsReserve": 0
    }
}

**/